//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scherzl.
        /// </summary>
        public static string BreadKindScherzl {
            get {
                return ResourceManager.GetString("BreadKindScherzl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ein Scherzl.
        /// </summary>
        public static string BreadKindScherzlOrderSentenceText {
            get {
                return ResourceManager.GetString("BreadKindScherzlOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scherzl.
        /// </summary>
        public static string BreadKindScherzlSynonyms {
            get {
                return ResourceManager.GetString("BreadKindScherzlSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schwoazbrot.
        /// </summary>
        public static string BreadKindSchwoazbrot {
            get {
                return ResourceManager.GetString("BreadKindSchwoazbrot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ein Schwoazbrot.
        /// </summary>
        public static string BreadKindSchwoazbrotOrderSentenceText {
            get {
                return ResourceManager.GetString("BreadKindSchwoazbrotOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schwoazbrot,brot,dunkles brot,dunkles,schwarzes.
        /// </summary>
        public static string BreadKindSchwoazbrotSynonyms {
            get {
                return ResourceManager.GetString("BreadKindSchwoazbrotSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semmö.
        /// </summary>
        public static string BreadKindSemmoe {
            get {
                return ResourceManager.GetString("BreadKindSemmoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eine Semmö.
        /// </summary>
        public static string BreadKindSemmoeOrderSentenceText {
            get {
                return ResourceManager.GetString("BreadKindSemmoeOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semmö,semmel.
        /// </summary>
        public static string BreadKindSemmoeSynonyms {
            get {
                return ResourceManager.GetString("BreadKindSemmoeSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soizgebäck.
        /// </summary>
        public static string BreadKindSoizgebaeck {
            get {
                return ResourceManager.GetString("BreadKindSoizgebaeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ein Soizgebäck.
        /// </summary>
        public static string BreadKindSoizgebaeckOrderSentenceText {
            get {
                return ResourceManager.GetString("BreadKindSoizgebaeckOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to soizgebäck,salzgebäck.
        /// </summary>
        public static string BreadKindSoizgebaeckSynonyms {
            get {
                return ResourceManager.GetString("BreadKindSoizgebaeckSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heit ka Wurscht fia di? Ka Problem, bis zum nächstn moi!.
        /// </summary>
        public static string CancelOrderConfirmation {
            get {
                return ResourceManager.GetString("CancelOrderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abbrechen,breche ab.
        /// </summary>
        public static string CancelOrderSynonyms {
            get {
                return ResourceManager.GetString("CancelOrderSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja,jo,passt,perfekt,super,gut,guat.
        /// </summary>
        public static string ConfirmOrder {
            get {
                return ResourceManager.GetString("ConfirmOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufschneiden.
        /// </summary>
        public static string CutKindAufschneiden {
            get {
                return ResourceManager.GetString("CutKindAufschneiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aufgeschnitten.
        /// </summary>
        public static string CutKindAufschneidenOrderSentenceText {
            get {
                return ResourceManager.GetString("CutKindAufschneidenOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aufgeschnitten,geschnitten,gschnitten.
        /// </summary>
        public static string CutKindAufschneidenSynonyms {
            get {
                return ResourceManager.GetString("CutKindAufschneidenSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Im Gonzn.
        /// </summary>
        public static string CutKindImGonzn {
            get {
                return ResourceManager.GetString("CutKindImGonzn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to im Gonzn.
        /// </summary>
        public static string CutKindImGonznOrderSentenceText {
            get {
                return ResourceManager.GetString("CutKindImGonznOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in gonzn,gonz,im ganzen,in ganzen,ganz.
        /// </summary>
        public static string CutKindImGonznSynonyms {
            get {
                return ResourceManager.GetString("CutKindImGonznSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwa Höften.
        /// </summary>
        public static string CutKindZwaHoeften {
            get {
                return ResourceManager.GetString("CutKindZwaHoeften", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in zwa Höften.
        /// </summary>
        public static string CutKindZwaHoeftenOrderSentenceText {
            get {
                return ResourceManager.GetString("CutKindZwaHoeftenOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to höften,helften,helfte,zwei helften,zwa helften,zwo helften,zwei helfte,zwa helfte,zwo helfte,zwei höften,zwo höften.
        /// </summary>
        public static string CutKindZwaHoeftenSynonyms {
            get {
                return ResourceManager.GetString("CutKindZwaHoeftenSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nein,ändern,anders.
        /// </summary>
        public static string DeclineOrder {
            get {
                return ResourceManager.GetString("DeclineOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menü,speisekarte.
        /// </summary>
        public static string GetMenuSynonyms {
            get {
                return ResourceManager.GetString("GetMenuSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hob di net goanz verstoandn..
        /// </summary>
        public static string IDidNotUnderstandYou {
            get {
                return ResourceManager.GetString("IDidNotUnderstandYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seas! I bin CurryWursch26, wöltweit da beste Currywurscht-Bot! Ba mia koanst du a gschmackige Currywurscht b&apos;stelln, natiarli mit Senf und oder Ketchup und Gurkerl oder Pfeffaroni..
        /// </summary>
        public static string InitialGreeting {
            get {
                return ResourceManager.GetString("InitialGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heit gibt&apos;s Woidviertla, Buarn, Schoafe und Eitrige, mit Senf und Ketchup und dazua Gurkerl oda Pfeffaroni..
        /// </summary>
        public static string MenuInformation {
            get {
                return ResourceManager.GetString("MenuInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to und.
        /// </summary>
        public static string OrderSentenceAnd {
            get {
                return ResourceManager.GetString("OrderSentenceAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Also, eine.
        /// </summary>
        public static string OrderSentenceBegin {
            get {
                return ResourceManager.GetString("OrderSentenceBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passt&apos;s so?.
        /// </summary>
        public static string OrderSentenceIsItFineLikeThat {
            get {
                return ResourceManager.GetString("OrderSentenceIsItFineLikeThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dazu.
        /// </summary>
        public static string OrderSentenceWith {
            get {
                return ResourceManager.GetString("OrderSentenceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beides.
        /// </summary>
        public static string SauceBeides {
            get {
                return ResourceManager.GetString("SauceBeides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit Senf und Ketchup.
        /// </summary>
        public static string SauceBeidesOrderSentenceTextDativ {
            get {
                return ResourceManager.GetString("SauceBeidesOrderSentenceTextDativ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senf und Ketchup.
        /// </summary>
        public static string SauceBeidesOrderSentenceTextNominativ {
            get {
                return ResourceManager.GetString("SauceBeidesOrderSentenceTextNominativ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beide,beide sauce.
        /// </summary>
        public static string SauceBeidesSynonyms {
            get {
                return ResourceManager.GetString("SauceBeidesSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ketchup.
        /// </summary>
        public static string SauceKetchup {
            get {
                return ResourceManager.GetString("SauceKetchup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit Ketchup.
        /// </summary>
        public static string SauceKetchupOrderSentenceTextDativ {
            get {
                return ResourceManager.GetString("SauceKetchupOrderSentenceTextDativ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ketchup.
        /// </summary>
        public static string SauceKetchupOrderSentenceTextNominativ {
            get {
                return ResourceManager.GetString("SauceKetchupOrderSentenceTextNominativ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ketchup.
        /// </summary>
        public static string SauceKetchupSynonyms {
            get {
                return ResourceManager.GetString("SauceKetchupSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daneben.
        /// </summary>
        public static string SaucePositionDaneben {
            get {
                return ResourceManager.GetString("SaucePositionDaneben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daneben.
        /// </summary>
        public static string SaucePositionDanebenOrderSentenceText {
            get {
                return ResourceManager.GetString("SaucePositionDanebenOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neben.
        /// </summary>
        public static string SaucePositionDanebenSynonyms {
            get {
                return ResourceManager.GetString("SaucePositionDanebenSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drauf.
        /// </summary>
        public static string SaucePositionDrauf {
            get {
                return ResourceManager.GetString("SaucePositionDrauf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drauf.
        /// </summary>
        public static string SaucePositionDraufOrderSentenceText {
            get {
                return ResourceManager.GetString("SaucePositionDraufOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to darauf.
        /// </summary>
        public static string SaucePositionDraufSynonyms {
            get {
                return ResourceManager.GetString("SaucePositionDraufSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senf.
        /// </summary>
        public static string SauceSenf {
            get {
                return ResourceManager.GetString("SauceSenf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit Senf.
        /// </summary>
        public static string SauceSenfOrderSentenceTextDativ {
            get {
                return ResourceManager.GetString("SauceSenfOrderSentenceTextDativ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senf.
        /// </summary>
        public static string SauceSenfOrderSentenceTextNominativ {
            get {
                return ResourceManager.GetString("SauceSenfOrderSentenceTextNominativ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to senf.
        /// </summary>
        public static string SauceSenfSynonyms {
            get {
                return ResourceManager.GetString("SauceSenfSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schoaf.
        /// </summary>
        public static string SauceTasteSchoaf {
            get {
                return ResourceManager.GetString("SauceTasteSchoaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schoaf.
        /// </summary>
        public static string SauceTasteSchoafOrderSentenceText {
            get {
                return ResourceManager.GetString("SauceTasteSchoafOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scharf.
        /// </summary>
        public static string SauceTasteSchoafSynonyms {
            get {
                return ResourceManager.GetString("SauceTasteSchoafSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siaß.
        /// </summary>
        public static string SauceTasteSiass {
            get {
                return ResourceManager.GetString("SauceTasteSiass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to siaß.
        /// </summary>
        public static string SauceTasteSiassOrderSentenceText {
            get {
                return ResourceManager.GetString("SauceTasteSiassOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to süß,süss,siass.
        /// </summary>
        public static string SauceTasteSiassSynonyms {
            get {
                return ResourceManager.GetString("SauceTasteSiassSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buren.
        /// </summary>
        public static string SausageKindBuren {
            get {
                return ResourceManager.GetString("SausageKindBuren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buren.
        /// </summary>
        public static string SausageKindBurenOrderSentenceText {
            get {
                return ResourceManager.GetString("SausageKindBurenOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buren,burenheidl.
        /// </summary>
        public static string SausageKindBurenSynonyms {
            get {
                return ResourceManager.GetString("SausageKindBurenSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käsekrainer.
        /// </summary>
        public static string SausageKindKaesekrainer {
            get {
                return ResourceManager.GetString("SausageKindKaesekrainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Käsekrainer.
        /// </summary>
        public static string SausageKindKaesekrainerOrderSentenceText {
            get {
                return ResourceManager.GetString("SausageKindKaesekrainerOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to käsekrainer.
        /// </summary>
        public static string SausageKindKaesekrainerSynonyms {
            get {
                return ResourceManager.GetString("SausageKindKaesekrainerSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schoafe.
        /// </summary>
        public static string SausageKindSchoafe {
            get {
                return ResourceManager.GetString("SausageKindSchoafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schoafe.
        /// </summary>
        public static string SausageKindSchoafeOrderSentenceText {
            get {
                return ResourceManager.GetString("SausageKindSchoafeOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schafe.
        /// </summary>
        public static string SausageKindSchoafeSynonyms {
            get {
                return ResourceManager.GetString("SausageKindSchoafeSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woidvierdler.
        /// </summary>
        public static string SausageKindWoidvierdler {
            get {
                return ResourceManager.GetString("SausageKindWoidvierdler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woidvierdler.
        /// </summary>
        public static string SausageKindWoidvierdlerOrderSentenceText {
            get {
                return ResourceManager.GetString("SausageKindWoidvierdlerOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to woidvierdler,woidvialda,rauchwuascht,rauchwiaschtl.
        /// </summary>
        public static string SausageKindWoidvierdlerSynonyms {
            get {
                return ResourceManager.GetString("SausageKindWoidvierdlerSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gurkel.
        /// </summary>
        public static string SideGurkel {
            get {
                return ResourceManager.GetString("SideGurkel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit Gurkel.
        /// </summary>
        public static string SideGurkelOrderSentenceText {
            get {
                return ResourceManager.GetString("SideGurkelOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gurken.
        /// </summary>
        public static string SideGurkelSynonyms {
            get {
                return ResourceManager.GetString("SideGurkelSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nix.
        /// </summary>
        public static string SideNix {
            get {
                return ResourceManager.GetString("SideNix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ohne ana Beiloag.
        /// </summary>
        public static string SideNixOrderSentenceText {
            get {
                return ResourceManager.GetString("SideNixOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nichts,keine,nein.
        /// </summary>
        public static string SideNixSynonyms {
            get {
                return ResourceManager.GetString("SideNixSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pfeffaroni.
        /// </summary>
        public static string SidePfeffaroni {
            get {
                return ResourceManager.GetString("SidePfeffaroni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mit Pfeffaroni.
        /// </summary>
        public static string SidePfeffaroniOrderSentenceText {
            get {
                return ResourceManager.GetString("SidePfeffaroniOrderSentenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pfeffaroni.
        /// </summary>
        public static string SidePfeffaroniSynonyms {
            get {
                return ResourceManager.GetString("SidePfeffaroniSynonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doangschen! Dei Currywurscht is do. Foilst nu woas bestön mechast soagst&apos;as hoit..
        /// </summary>
        public static string ThankYouYourOrderIsReady {
            get {
                return ResourceManager.GetString("ThankYouYourOrderIsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wos meachst du?.
        /// </summary>
        public static string WhatDoYouWantToOrder {
            get {
                return ResourceManager.GetString("WhatDoYouWantToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woas meachat&apos;ns oanders hob&apos;n?.
        /// </summary>
        public static string WhatEleseWouldYouLikeToHave {
            get {
                return ResourceManager.GetString("WhatEleseWouldYouLikeToHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wöches Brot?.
        /// </summary>
        public static string WhichBread {
            get {
                return ResourceManager.GetString("WhichBread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie?.
        /// </summary>
        public static string WhichCutKind {
            get {
                return ResourceManager.GetString("WhichCutKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wöcha Sauce?.
        /// </summary>
        public static string WhichSauce {
            get {
                return ResourceManager.GetString("WhichSauce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drauf oder daneben?.
        /// </summary>
        public static string WhichSaucePosition {
            get {
                return ResourceManager.GetString("WhichSaucePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wöchan?.
        /// </summary>
        public static string WhichSauceTaste {
            get {
                return ResourceManager.GetString("WhichSauceTaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wöcha Wurscht?.
        /// </summary>
        public static string WhichSausage {
            get {
                return ResourceManager.GetString("WhichSausage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wöcha Beiloag?.
        /// </summary>
        public static string WhichSide {
            get {
                return ResourceManager.GetString("WhichSide", resourceCulture);
            }
        }
    }
}
